### ISSUE TITLE
System.Text.Json Support?

### ISSUE THREAD

**Issue by bgribaudo** [iwate/ODataHttpClient#20]
Hello,

Thank you for ODataHttpClient! I was wondering if you have any plans to support serialization using System.Text.Json?

Thanks,
Ben

**Comment by iwate** [comment]
Hi, @bgribaudo 

I know Systenm.Text.Json is good for save memory and it is faster than newtonsoft.json.
However I do not think to support System.Text.Json because this lib need json path query.

I design this lib to use easy like as script lang.

For example, the following code is easy when use json path query. 
But, If json path query is not supported, It need to create all classes and long linq query. (Of course, it is good for static typing validation:)  but it is not a motivation for this lib.

```
var link = search.ReadAs<string>($"$.data[?(@.id=='{id}')].versions[0]['@id']");
```

Thank you for your feedback!

**Comment by bgribaudo** [comment]
Thanks, @iwate!
